### ISSUE TITLE
which end is up? (getting started)

### ISSUE THREAD

**Issue by dckc** [zenhack/sandstorm-filesystem#1]
I've only done a little go coding, and it was a while ago, so I'm not sure how to get started.

I tried `make` but I got `"cannot find package "github.com/gorilla/mux"`.
Then I tried `go get` but I got
```
package zenhack.net/go/sandstorm-filesystem/filesystem: unrecognized import path "zenhack.net/go/sandstorm-filesystem/filesystem" (parse https://zenhack.net/go/sandstorm-filesystem/filesystem?go-get=1: no go-import meta tags ())
package zenhack.net/go/sandstorm-filesystem/filesystem/httpfs: unrecognized import path "zenhack.net/go/sandstorm-filesystem/filesystem/httpfs" (parse https://zenhack.net/go/sandstorm-filesystem/filesystem/httpfs?go-get=1: no go-import meta tags ())
package zenhack.net/go/sandstorm-filesystem/filesystem/local: unrecognized import path "zenhack.net/go/sandstorm-filesystem/filesystem/local" (parse https://zenhack.net/go/sandstorm-filesystem/filesystem/local?go-get=1: no go-import meta tags ())
```

**Comment by zenhack** [comment]
D'oh -- looks like I forgot to actually set up the redirect for this one. I'll fix it soon, but you can hack around it by just cloning into $GOPATH/src/zenhack.net/go/sandstorm-filesystem manually.

**Comment by dckc** [comment]
thanks for the pointer to [June 8 sandstorm-dev discussion](https://groups.google.com/forum/#!searchin/sandstorm-dev/sandstorm-filesystem%7Csort:relevance/sandstorm-dev/sjEldWXrAjc/zjNGGdMpCAAJ)

**Comment by zenhack** [comment]
So, I think you've sorted through this at some point, and the things that came up have been added to the README (I've also added the link to the mailing list post), and the go get redirect is fixed, so I'm going to close this -- there's nothing really actionable left I think.
